inherit_gem:
  relaxed-rubocop: .rubocop.yml
require:
  - rubocop-rails
Metrics/BlockLength:
  Exclude:
    - 'db/migrate/*'
    - 'db/schema.rb'
    - 'Rakefile'
    - '**/*.rake'
    - 'test/**/*.rb'
    - 'config/**/*.rb'
Style/ClassAndModuleChildren:
  Exclude:
    - 'test/**/*.rb'
AllCops:
  NewCops: enable
Rails/FilePath:
  Enabled: false
Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
Rails/Output:
  Exclude:
    - 'db/**/*.rb'
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Rails/SkipsModelValidations:
  Exclude:
    - 'db/**/*.rb'
Rails/ApplicationRecord:
  Exclude:
    - 'db/**/*.rb'
Style/ExplicitBlockArgument:
  Enabled: false
